#!/usr/bin/env python3
"""
Museum security robot - LLM high-level command interface.

Architecture (this file is the top box only):

    operator text
         |
         v
    +----------------------+   tool call    +------------------------+
    |  Gemini LLM          | -------------> |  semantic -> coordinate|
    |  prompts/*.txt       |                |  config/locations.json |
    |  config/llm_tools.js |                +------------------------+
    +----------------------+                          |
                                                      v
                                        nav2_simple_commander BasicNavigator
                                                      |
                                        NavigateToPose action -> Nav2
                                                      |
                                     planner -> controller -> /cmd_vel -> Gazebo

The LLM never computes a path and never emits a velocity. It only chooses
WHICH named place to go. Everything below the dashed line is Nav2's job.

Usage:
    ros2 run museum_security_robot museum_ai_navigator            # AI mode
    ros2 run museum_security_robot museum_ai_navigator --menu     # no LLM
    ros2 run museum_security_robot museum_ai_navigator --goto cafeteria
    ros2 run museum_security_robot museum_ai_navigator --patrol
"""

import argparse
import json
import math
import os
import sys
import time

import rclpy
from ament_index_python.packages import get_package_share_directory
from geometry_msgs.msg import PoseStamped
from nav2_simple_commander.robot_navigator import BasicNavigator, TaskResult

PKG = "museum_security_robot"


# ===========================================================================
# 1. SEMANTIC -> COORDINATE MAPPING
# ===========================================================================

def load_locations():
    """Load the room table generated by tools/generate_world.py.

    Reading this from a file rather than hardcoding a dict is deliberate: the
    same file is generated from the world geometry, so the waypoints can never
    drift out of sync with the walls the way hand-typed coordinates do.
    """
    share = get_package_share_directory(PKG)
    path = os.path.join(share, "config", "locations.json")
    with open(path) as f:
        data = json.load(f)
    return data["locations"], data["spawn_pose"]


def load_tools():
    share = get_package_share_directory(PKG)
    with open(os.path.join(share, "config", "llm_tools.json")) as f:
        return json.load(f)["tools"]


def load_system_prompt(locations):
    share = get_package_share_directory(PKG)
    with open(os.path.join(share, "prompts", "system_prompt.txt")) as f:
        template = f.read()
    table = "\n".join(
        f'  - "{k}": {v["description"]}  (map x={v["x"]}, y={v["y"]})'
        for k, v in locations.items()
    )
    return template.replace("{location_table}", table)


def yaw_to_quaternion(yaw):
    """A yaw-only rotation is (0, 0, sin(yaw/2), cos(yaw/2)).

    Note w = cos(yaw/2), which is 1.0 for yaw = 0 - never all zeros. An
    all-zero quaternion is not a rotation at all and AMCL/Nav2 will reject it.
    """
    return 0.0, 0.0, math.sin(yaw / 2.0), math.cos(yaw / 2.0)


def make_pose(navigator, x, y, yaw):
    p = PoseStamped()
    p.header.frame_id = "map"
    p.header.stamp = navigator.get_clock().now().to_msg()
    p.pose.position.x = float(x)
    p.pose.position.y = float(y)
    p.pose.position.z = 0.0
    (p.pose.orientation.x, p.pose.orientation.y,
     p.pose.orientation.z, p.pose.orientation.w) = yaw_to_quaternion(yaw)
    return p


# ===========================================================================
# 2. LLM INTENT PARSING (tool calling)
# ===========================================================================

class MuseumBrain:
    """Wraps Gemini. Returns a (tool_name, arguments) pair, or None on failure.

    Returning None instead of a default destination is a deliberate design
    choice. The original version caught every exception and silently returned
    "lobby", which meant a dead network looked identical to a correct
    decision. During a live demo that is the worst possible failure mode.
    """

    def __init__(self, locations, model="gemini-3.5-flash"):
        self.available = False
        self.model = model
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            print("[LLM] GEMINI_API_KEY is not set - AI mode unavailable.")
            print("      export GEMINI_API_KEY='...'  or run with --menu")
            return
        try:
            from google import genai
            from google.genai import types
            self._types = types
            self.client = genai.Client(api_key=api_key)
            self.system_prompt = load_system_prompt(locations)
            self.tools = [types.Tool(function_declarations=load_tools())]
            self.available = True
        except Exception as exc:                      # noqa: BLE001
            print(f"[LLM] could not initialise Gemini client: {exc}")

    def interpret(self, text):
        if not self.available:
            return None
        try:
            resp = self.client.models.generate_content(
                model=self.model,
                contents=text,
                config=self._types.GenerateContentConfig(
                    system_instruction=self.system_prompt,
                    tools=self.tools,
                    # Forcing ANY means the model must emit a tool call rather
                    # than free prose, which removes a whole class of parsing
                    # bugs - no regex, no JSON scraping, no punctuation issues.
                    tool_config=self._types.ToolConfig(
                        function_calling_config=self._types.FunctionCallingConfig(
                            mode="ANY")),
                    temperature=0.0,
                ),
            )
        except Exception as exc:                      # noqa: BLE001
            print(f"[LLM] API call FAILED: {exc}")
            return None

        for part in (resp.candidates[0].content.parts or []):
            if getattr(part, "function_call", None):
                fc = part.function_call
                return fc.name, dict(fc.args or {})
        print("[LLM] model returned no tool call - treating as a failure.")
        return None


# ===========================================================================
# 3. ROBOT EXECUTION
# ===========================================================================

class SecurityPatrol:

    def __init__(self, locations, spawn):
        self.locations = locations
        self.spawn = spawn
        self.nav = BasicNavigator()

    def start(self, set_initial_pose=True):
        if set_initial_pose:
            # AMCL is a LOCAL filter - it refines a pose you give it, it cannot
            # find the robot from scratch. Without this call
            # waitUntilNav2Active() publishes a default-constructed pose whose
            # quaternion is (0,0,0,0), which is not a valid rotation.
            init = make_pose(self.nav, self.spawn["x"], self.spawn["y"],
                             self.spawn["yaw"])
            self.nav.setInitialPose(init)
            print(f"[nav] initial pose set to x={self.spawn['x']:.2f} "
                  f"y={self.spawn['y']:.2f} yaw={self.spawn['yaw']:.2f}")

        print("[nav] waiting for Nav2 lifecycle nodes to activate...")
        self.nav.waitUntilNav2Active()
        print("[nav] Nav2 is active.")

    def go(self, name, timeout=180.0):
        loc = self.locations[name]
        goal = make_pose(self.nav, loc["x"], loc["y"], loc["yaw"])
        print(f"[nav] -> {name}  (x={loc['x']:.2f}, y={loc['y']:.2f})")
        self.nav.goToPose(goal)

        t0, last = time.time(), 0.0
        while not self.nav.isTaskComplete():
            fb = self.nav.getFeedback()
            if fb and time.time() - last > 2.0:
                last = time.time()
                # distance_remaining is measured along the planned path, so it
                # is longer than the straight-line distance - that is correct,
                # not a bug.
                print(f"      {fb.distance_remaining:5.2f} m remaining")
            if time.time() - t0 > timeout:
                print("[nav] timeout - cancelling goal")
                self.nav.cancelTask()
                return False
            time.sleep(0.1)

        result = self.nav.getResult()
        if result == TaskResult.SUCCEEDED:
            print(f"[nav] arrived at {name}. Area secure.\n")
            return True
        if result == TaskResult.CANCELED:
            print("[nav] goal was cancelled.\n")
        else:
            # Common causes: goal inside the inflation layer, AMCL diverged,
            # or the global planner could not find a route through unknown
            # space (allow_unknown is false by design).
            print(f"[nav] FAILED to reach {name}.\n")
        return False

    def patrol(self, names):
        print(f"[nav] patrol route: {' -> '.join(names)}")
        reached = [n for n in names if self.go(n)]
        print(f"[nav] patrol finished: {len(reached)}/{len(names)} stops reached.\n")

    def shutdown(self):
        self.nav.destroyNode()


# ===========================================================================
# 4. TOOL DISPATCH
# ===========================================================================

def dispatch(patrol, tool, args):
    if tool == "navigate_to":
        name = args.get("location")
        if name not in patrol.locations:
            print(f"[!] LLM returned an unknown location '{name}' - ignoring.")
            return
        print(f"[ai] reason: {args.get('reason', '(none given)')}")
        patrol.go(name)

    elif tool == "patrol_route":
        names = [n for n in args.get("locations", []) if n in patrol.locations]
        if not names:
            print("[!] LLM returned no usable locations - ignoring.")
            return
        print(f"[ai] reason: {args.get('reason', '(none given)')}")
        patrol.patrol(names)

    elif tool == "report_status":
        print(f"[ai] {args.get('answer', '')}")

    elif tool == "reject_command":
        print(f"[ai] declined: {args.get('explanation', '')}")

    else:
        print(f"[!] unknown tool '{tool}'")


# ===========================================================================
# 5. OPERATOR INTERFACES
# ===========================================================================

BANNER = """
=====================================================================
  MUSEUM SECURITY ROBOT - AI COMMAND CONSOLE
=====================================================================
  Speak to it in plain English. Some things to try:

    I think someone is messing with the servers
    Did I leave my backpack near the old bones?
    There's a kid climbing on the marble figure
    Check where people eat, someone reported a spill
    Somebody just walked in the front door
    Is anyone trying to sneak out the back?
    Head back to the monitoring station
    Sweep the west half of the building
    Do a full round of the museum
    Where are you right now?

  Commands:  list | menu | exit
=====================================================================
"""


def menu_mode(patrol):
    """Numbered semantic-location menu - the non-LLM control path.

    The project brief asks for a menu program that lists predefined semantic
    locations and publishes the matching goal pose. This is that, and it also
    gives you a working demo if the network or API key fails on demo day.
    """
    names = list(patrol.locations)
    while True:
        print("\n--- MUSEUM NAVIGATION MENU ---")
        for i, n in enumerate(names, 1):
            print(f"  {i}. {n:<22} {patrol.locations[n]['description']}")
        print("  0. exit")
        raw = input("select > ").strip()
        if raw in ("0", "exit", "quit"):
            return
        if not raw.isdigit() or not 1 <= int(raw) <= len(names):
            print("invalid selection")
            continue
        patrol.go(names[int(raw) - 1])


def ai_mode(patrol, brain):
    print(BANNER)
    while True:
        try:
            text = input("Commander > ").strip()
        except EOFError:
            return
        if not text:
            continue
        low = text.lower()
        if low in ("exit", "quit"):
            return
        if low == "menu":
            menu_mode(patrol)
            continue
        if low == "list":
            for n, l in patrol.locations.items():
                print(f"  {n:<22} {l['description']}")
            continue

        print("[ai] thinking...")
        decision = brain.interpret(text)
        if decision is None:
            # Explicit, loud, and does NOT move the robot.
            print("[ai] >>> LLM UNAVAILABLE - no action taken. "
                  "Use 'menu' to drive manually. <<<\n")
            continue
        dispatch(patrol, *decision)


# ===========================================================================
# 6. ENTRY POINT
# ===========================================================================

def main(argv=None):
    ap = argparse.ArgumentParser(description="Museum security robot commander")
    ap.add_argument("--menu", action="store_true",
                    help="numbered location menu, no LLM required")
    ap.add_argument("--goto", metavar="LOCATION",
                    help="drive to one location and exit (for scripted demos)")
    ap.add_argument("--patrol", action="store_true",
                    help="run a full circuit of every location and exit")
    ap.add_argument("--no-initial-pose", action="store_true",
                    help="skip setInitialPose (use if you set it in RViz)")
    ap.add_argument("--model", default="gemini-3.5-flash")
    args, ros_args = ap.parse_known_args(argv if argv is not None else sys.argv[1:])

    rclpy.init(args=ros_args)
    locations, spawn = load_locations()
    patrol = SecurityPatrol(locations, spawn)

    try:
        patrol.start(set_initial_pose=not args.no_initial_pose)

        if args.goto:
            if args.goto not in locations:
                print(f"unknown location '{args.goto}'. "
                      f"Known: {', '.join(locations)}")
            else:
                patrol.go(args.goto)
        elif args.patrol:
            patrol.patrol(list(locations))
        elif args.menu:
            menu_mode(patrol)
        else:
            brain = MuseumBrain(locations, model=args.model)
            if not brain.available:
                print("Falling back to the manual menu.\n")
                menu_mode(patrol)
            else:
                ai_mode(patrol, brain)
    except KeyboardInterrupt:
        print("\ninterrupted")
    finally:
        patrol.shutdown()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
